openapi: 3.2.0
info:
  title: Blnk Backup API
  contact: {}
  version: '1.0'
servers:
- url: http://localhost:5001
  variables: {}
security: []
tags:
- name: Backup
paths:
  /backup:
    post:
      summary: Back DB
      operationId: BackDB
      parameters: []
      responses:
        '201':
          description: Created
          headers:
            Date:
              content:
                text/plain:
                  schema:
                    type: string
                  example: Tue, 20 Feb 2024 05:42:41 GMT
            Content-Length:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '645'
          content:
            application/json; charset=utf-8:
              schema:
                allOf:
                - $ref: '#/components/schemas/CreateEvent'
                - example:
                    id: txn_ea438725-e677-405c-9552-4c549837c622
                    tag: ''
                    reference: 1jhbs3ozmen0k7y5e333feeme3rrr33ewwedffdew
                    amount: 30000
                    currency: NGN
                    payment_method: ''
                    description: ''
                    drcr: Credit
                    status: QUEUED
                    ledger_id: ldg_073f7ffe-9dfd-42ce-aa50-d1dca1788adc
                    balance_id: bln_0be360ca-86fe-457d-be43-daa3f966d8f0
                    credit_balance_before: 600
                    debit_balance_before: 300
                    credit_balance_after: 30600
                    debit_balance_after: 300
                    balance_before: 300
                    balance_after: 30300
                    created_at: '2024-02-20T05:42:41.686457754Z'
                    scheduled_for: '0001-01-01T00:00:00Z'
                    risk_tolerance_threshold: 0
                    risk_score: 0.12020571428571429
                    group_ids: null
              example:
                id: txn_ea438725-e677-405c-9552-4c549837c622
                tag: ''
                reference: 1jhbs3ozmen0k7y5e333feeme3rrr33ewwedffdew
                amount: 30000
                currency: NGN
                payment_method: ''
                description: ''
                drcr: Credit
                status: QUEUED
                ledger_id: ldg_073f7ffe-9dfd-42ce-aa50-d1dca1788adc
                balance_id: bln_0be360ca-86fe-457d-be43-daa3f966d8f0
                credit_balance_before: 600
                debit_balance_before: 300
                credit_balance_after: 30600
                debit_balance_after: 300
                balance_before: 300
                balance_after: 30300
                created_at: '2024-02-20T05:42:41.686457754Z'
                scheduled_for: '0001-01-01T00:00:00Z'
                risk_tolerance_threshold: 0
                risk_score: 0.12020571428571429
                group_ids: null
      deprecated: false
      tags:
      - Backup
  /backup/s3:
    post:
      summary: Back DB To S3
      operationId: BackDBToS3
      parameters: []
      responses:
        '201':
          description: Created
          headers:
            Date:
              content:
                text/plain:
                  schema:
                    type: string
                  example: Tue, 20 Feb 2024 05:42:41 GMT
            Content-Length:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '645'
          content:
            application/json; charset=utf-8:
              schema:
                allOf:
                - $ref: '#/components/schemas/CreateEvent'
                - example:
                    id: txn_ea438725-e677-405c-9552-4c549837c622
                    tag: ''
                    reference: 1jhbs3ozmen0k7y5e333feeme3rrr33ewwedffdew
                    amount: 30000
                    currency: NGN
                    payment_method: ''
                    description: ''
                    drcr: Credit
                    status: QUEUED
                    ledger_id: ldg_073f7ffe-9dfd-42ce-aa50-d1dca1788adc
                    balance_id: bln_0be360ca-86fe-457d-be43-daa3f966d8f0
                    credit_balance_before: 600
                    debit_balance_before: 300
                    credit_balance_after: 30600
                    debit_balance_after: 300
                    balance_before: 300
                    balance_after: 30300
                    created_at: '2024-02-20T05:42:41.686457754Z'
                    scheduled_for: '0001-01-01T00:00:00Z'
                    risk_tolerance_threshold: 0
                    risk_score: 0.12020571428571429
                    group_ids: null
              example:
                id: txn_ea438725-e677-405c-9552-4c549837c622
                tag: ''
                reference: 1jhbs3ozmen0k7y5e333feeme3rrr33ewwedffdew
                amount: 30000
                currency: NGN
                payment_method: ''
                description: ''
                drcr: Credit
                status: QUEUED
                ledger_id: ldg_073f7ffe-9dfd-42ce-aa50-d1dca1788adc
                balance_id: bln_0be360ca-86fe-457d-be43-daa3f966d8f0
                credit_balance_before: 600
                debit_balance_before: 300
                credit_balance_after: 30600
                debit_balance_after: 300
                balance_before: 300
                balance_after: 30300
                created_at: '2024-02-20T05:42:41.686457754Z'
                scheduled_for: '0001-01-01T00:00:00Z'
                risk_tolerance_threshold: 0
                risk_score: 0.12020571428571429
                group_ids: null
      deprecated: false
      tags:
      - Backup
components:
  schemas:
    CreateEvent:
      title: CreateEvent
      required:
      - id
      - tag
      - reference
      - amount
      - currency
      - payment_method
      - description
      - drcr
      - status
      - ledger_id
      - balance_id
      - credit_balance_before
      - debit_balance_before
      - credit_balance_after
      - debit_balance_after
      - balance_before
      - balance_after
      - created_at
      - scheduled_for
      - risk_tolerance_threshold
      - risk_score
      - group_ids
      type: object
      properties:
        id:
          type: string
        tag:
          type: string
        reference:
          type: string
        amount:
          type: integer
          format: int32
        currency:
          type: string
        payment_method:
          type: string
        description:
          type: string
        drcr:
          type: string
        status:
          type: string
        ledger_id:
          type: string
        balance_id:
          type: string
        credit_balance_before:
          type: integer
          format: int32
        debit_balance_before:
          type: integer
          format: int32
        credit_balance_after:
          type: integer
          format: int32
        debit_balance_after:
          type: integer
          format: int32
        balance_before:
          type: integer
          format: int32
        balance_after:
          type: integer
          format: int32
        created_at:
          type: string
        scheduled_for:
          type: string
        risk_tolerance_threshold:
          type: integer
          format: int32
        risk_score:
          type: number
        group_ids:
          type:
          - string
          - 'null'
      example:
        id: txn_ea438725-e677-405c-9552-4c549837c622
        tag: ''
        reference: 1jhbs3ozmen0k7y5e333feeme3rrr33ewwedffdew
        amount: 30000
        currency: NGN
        payment_method: ''
        description: ''
        drcr: Credit
        status: QUEUED
        ledger_id: ldg_073f7ffe-9dfd-42ce-aa50-d1dca1788adc
        balance_id: bln_0be360ca-86fe-457d-be43-daa3f966d8f0
        credit_balance_before: 600
        debit_balance_before: 300
        credit_balance_after: 30600
        debit_balance_after: 300
        balance_before: 300
        balance_after: 30300
        created_at: '2024-02-20T05:42:41.686457754Z'
        scheduled_for: '0001-01-01T00:00:00Z'
        risk_tolerance_threshold: 0
        risk_score: 0.12020571428571429
        group_ids: null
  securitySchemes:
    basic:
      type: http
      scheme: basic
