openapi: 3.2.0
info:
  title: Blnk Ledgers API
  contact: {}
  version: '1.0'
servers:
- url: http://localhost:5001
  variables: {}
security: []
tags:
- name: Ledgers
paths:
  /ledgers:
    post:
      summary: Create ledger
      operationId: Createledger
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/CreateledgerRequest'
              - example:
                  name: Customer wallets Ledger
                  meta_data:
                    project_owner: Blnk Tech
            example:
              name: Customer wallets Ledger
              meta_data:
                project_owner: Blnk Tech
        required: true
      responses:
        '201':
          description: Created
          headers:
            Date:
              content:
                text/plain:
                  schema:
                    type: string
                  example: Tue, 20 Feb 2024 05:28:03 GMT
            Content-Length:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '128'
          content:
            application/json; charset=utf-8:
              schema:
                allOf:
                - $ref: '#/components/schemas/Createledger'
                - example:
                    ledger_id: ldg_073f7ffe-9dfd-42ce-aa50-d1dca1788adc
                    name: Customer wallets Ledger
                    created_at: '2024-02-20T05:28:03.558281542Z'
                    meta_data:
                      project_owner: Blnk Tech
              example:
                ledger_id: ldg_073f7ffe-9dfd-42ce-aa50-d1dca1788adc
                name: Customer wallets Ledger
                created_at: '2024-02-20T05:28:03.558281542Z'
                meta_data:
                  project_owner: Blnk Tech
      deprecated: false
      security:
      - basic: []
      tags:
      - Ledgers
  /ledgers/{ledger_id}:
    get:
      summary: Get Ledger
      operationId: GetLedger
      parameters:
      - name: ledger_id
        in: path
        description: Unique identification number for your ledger
        required: true
        style: simple
        schema:
          type: string
          example: ldg_073f7ffe-9dfd-42ce-aa50-d1dca1788adc
      responses:
        '200':
          description: OK
          headers:
            Date:
              content:
                text/plain:
                  schema:
                    type: string
                  example: Tue, 20 Feb 2024 05:43:29 GMT
            Content-Length:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '125'
          content:
            application/json; charset=utf-8:
              schema:
                allOf:
                - $ref: '#/components/schemas/Ledger'
                - example:
                    ledger_id: ldg_073f7ffe-9dfd-42ce-aa50-d1dca1788adc
                    name: Customer wallets Ledger
                    created_at: '2024-02-20T05:28:03.563132Z'
                    meta_data:
                      project_owner: Blnk Tech
              example:
                ledger_id: ldg_073f7ffe-9dfd-42ce-aa50-d1dca1788adc
                name: Customer wallets Ledger
                created_at: '2024-02-20T05:28:03.563132Z'
                meta_data:
                  project_owner: Blnk Tech
      deprecated: false
      tags:
      - Ledgers
components:
  schemas:
    Ledger:
      title: Ledger
      required:
      - ledger_id
      - name
      - created_at
      - meta_data
      type: object
      properties:
        ledger_id:
          type: string
        name:
          type: string
        created_at:
          type: string
        meta_data:
          $ref: '#/components/schemas/MetaData'
      example:
        ledger_id: ldg_073f7ffe-9dfd-42ce-aa50-d1dca1788adc
        name: Customer wallets Ledger
        created_at: '2024-02-20T05:28:03.563132Z'
        meta_data:
          project_owner: Blnk Tech
    CreateledgerRequest:
      title: CreateledgerRequest
      required:
      - name
      - meta_data
      type: object
      properties:
        name:
          type: string
        meta_data:
          $ref: '#/components/schemas/MetaData'
      example:
        name: Customer wallets Ledger
        meta_data:
          project_owner: Blnk Tech
    MetaData:
      title: MetaData
      required:
      - project_owner
      type: object
      properties:
        project_owner:
          type: string
      example:
        project_owner: Blnk Tech
    Createledger:
      title: Createledger
      required:
      - ledger_id
      - name
      - created_at
      - meta_data
      type: object
      properties:
        ledger_id:
          type: string
        name:
          type: string
        created_at:
          type: string
        meta_data:
          $ref: '#/components/schemas/MetaData'
      example:
        id: ldg_073f7ffe-9dfd-42ce-aa50-d1dca1788adc
        name: Customer wallets Ledger
        created_at: '2024-02-20T05:28:03.558281542Z'
        meta_data:
          project_owner: Blnk Tech
  securitySchemes:
    basic:
      type: http
      scheme: basic
